<?xml version='1.0' encoding='UTF-8' ?>
<!-- ******************************************************************************
*                 
*
* FILENAME:   test.wsdl
*
* 
****************************************************************************** --> 
<definitions
	name='test'
	targetNamespace='test.wsdl'
	xmlns:wsdlns='test.wsdl'
	xmlns:typens='test.type'
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
	xmlns:xsd='http://www.w3.org/2001/XMLSchema'
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
	xmlns='http://schemas.xmlsoap.org/wsdl/'>

	<types>
		<schema
			targetNamespace='test.type'
			xmlns='http://www.w3.org/2001/XMLSchema'
			elementFormDefault='qualified'>

			<!-- Driver general data -->
			<complexType  name='DATA_GENERAL'>
				<sequence>
					<element name='PINFA' type='xsd:int'/>			<!-- License Key (unsignedLong) -->
					<element name='AWNUM' type='xsd:int'/>			<!-- License Seq (unsignedShort) -->
					<element name='KTIDE' type='xsd:string'/>		<!-- Driver Kanton Code -->
					<element name='RGIDE' type='xsd:string'/>		<!-- Driver Id Number -->
					<element name='PRODST' type='xsd:string'/>		<!-- Driver License Site -->
					<element name='FNAME' type='xsd:string'/>		<!-- Driver Last Name 1 -->
					<element name='WNAME' type='xsd:string'/>		<!-- Driver Last Name 2 -->
					<element name='VNAME' type='xsd:string'/>		<!-- Driver First Name -->
					<element name='GEBDA' type='xsd:string'/>		<!-- Driver Date of Birth -->
					<element name='GESLE' type='xsd:string'/>		<!-- Driver Sex -->
					<element name='SPRAC' type='xsd:string'/>		<!-- Driver Language -->
					<element name='HEIMA' type='xsd:string'/>		<!-- Driver Birth Place -->
					<element name='AWBIS' type='xsd:string'/>		<!-- License Expiry -->
					<element name='AWKTN' type='xsd:string'/>		<!-- License Authority -->
					<element name='AUFLA' type='xsd:string'/>		<!-- License Details 1 -->
					<element name='AUFLB' type='xsd:string'/>		<!-- License Details 2 -->
					<element name='KMAT' type='xsd:string'/>		<!-- Material Code -->
					<element name='AUSWSPR' type='xsd:string'/>		<!-- License Language -->
					<element name='USER' type='xsd:string'/>		<!-- User name -->
					<element name='AWDAT' type='xsd:string'/>		<!-- Printing date -->
				</sequence>
			</complexType>

			<!-- printing output data -->
			<complexType  name='DATA_PRINT'>
				<sequence>
					<element name='ROHLG' type='xsd:string'/>		<!-- License Raw Material -->
				</sequence>
			</complexType>

			<!-- photo & signature, binary large objects -->
			<complexType  name='DATA_IMAGE'>
				<sequence>
					<element name='SPFMT' type='xsd:string'/>		<!-- format
																		photo: "JPG"
																		signature: "TIF" -->
					<element name='DIGDA' type='xsd:base64Binary'/>	<!-- image encoded as mime -->
				</sequence>
			</complexType>

			<!-- categories, maximum 25 -->
			<complexType name='DATA_CATEGORY'>
				<sequence>
					<element name='AWKAT' type='xsd:string'/>		<!-- Driver Category -->
					<element name='KPDAT' type='xsd:string'/>		<!-- Driver Category Start -->
					<element name='GILTB' type='xsd:string'/>		<!-- Driver Category Expiry -->
					<element name='BESCH' type='xsd:string'/>		<!-- Driver Category Limits -->
				</sequence>
			</complexType>

			<complexType name='DATA_CATEGORIES'>
				<sequence>
					<element
						name='DATA_CATEGORY'
						type='typens:DATA_CATEGORY'
						maxOccurs="unbounded"/>
				</sequence>
			</complexType>

			<!-- printers, maximum 10 -->
			<complexType  name='LICENSE_PRINTER'>
				<sequence>
					<element name='status' type='xsd:int'/>				
					<element name='PINFA' type='xsd:int'/>			 
					<element name='language' type='xsd:string'/>		
					<element name='queueSize' type='xsd:int'/>			<!-- Number of printing requests for this printer (unsignedInt) -->
				</sequence>
			</complexType>

			<complexType name='FAULT_DETAIL'>
				<sequence>
					<element name='language' type='xsd:string'/>		
					<element name='errorType' type='xsd:string'/>		
					<element name='errorClass' type='xsd:string'/>		
					<element name='errorCode' type='xsd:string'/>
					<element minOccurs="0" maxOccurs="1" name='errorPlace' type='xsd:int'/>
				</sequence>
			</complexType>

			<complexType name='JOB_FAULT'>
				<sequence>
					<element name='faultstring' type='xsd:string'/>
					<element name='faultactor' type='xsd:string'/>
					<element name='detail' type='typens:FAULT_DETAIL'/>
				</sequence>
			</complexType>

			<complexType name='PrintLicenseAutoResponse'>
				<sequence>
					<element name='DATA_PRINT' type='typens:DATA_PRINT'/>
					<element minOccurs="0" maxOccurs="1" name='fault' type='typens:JOB_FAULT'/>
				</sequence>
			</complexType>

			<complexType name='GetPrinterStatusResponse'>
				<sequence>
					<element name='LICENSE_PRINTER' type='typens:LICENSE_PRINTER'/>
					<element minOccurs="0" maxOccurs="1" name='fault' type='typens:JOB_FAULT'/>
				</sequence>
			</complexType>
		</schema>
	</types>

	<message name='PrintLicenseAutoRequest'>
		<part name='OriginMachine' type='xsd:string'/>
		<part name='DATA_GENERAL' type='typens:DATA_GENERAL'/>
		<part name='DATA_CATEGORIES' type='typens:DATA_CATEGORIES'/>
		<part name='DATA_DIGBI' type='typens:DATA_IMAGE'/>
		<part name='DATA_DIGSI' type='typens:DATA_IMAGE'/>
	</message>

	<message name='PrintLicenseAutoResponse'>
		<part name='Result' type='typens:PrintLicenseAutoResponse'/>
	</message>

	<message name='GetPrinterStatusRequest'>
		<part name='OriginMachine' type='xsd:string'/>
	</message>

	<message name='GetPrinterStatusResponse'>
		<part name='Result' type='typens:GetPrinterStatusResponse'/>
	</message>

	<message name='FaultDetail'>
		<part name='detail' element='typens:FAULT_DETAIL'/>
	</message>

	<portType name='Job2Port'>

		<operation name='PrintLicenseAuto' parameterOrder='OriginMachine DATA_GENERAL DATA_CATEGORIES DATA_DIGBI DATA_DIGSI'>
			<input message='wsdlns:PrintLicenseAutoRequest'/>
			<output message='wsdlns:PrintLicenseAutoResponse'/>
			<!--fault name='PrintLicenseAutoFault' message='wsdlns:FaultDetail'/-->
		</operation>

		<operation name='GetPrinterStatus' parameterOrder='OriginMachine'>
			<input message='wsdlns:GetPrinterStatusRequest'/>
			<output message='wsdlns:GetPrinterStatusResponse'/>
			<!--fault name='GetPrinterStatusFault' message='wsdlns:FaultDetail'/-->
		</operation>

	</portType>

	<binding name='Job2Binding' type='wsdlns:Job2Port' >
		<soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/>

		<operation name='PrintLicenseAuto'>
			<soap:operation soapAction='PrintLicenseAuto'/>
			<input>
				<soap:body 
					use='literal'
					namespace='test.message'
					parts='OriginMachine DATA_GENERAL DATA_CATEGORIES DATA_DIGBI DATA_DIGSI'/>
			</input>
			<output>
				<soap:body use='literal' namespace='Test.message' parts='Result'/>
			</output>
			<!--fault name='PrintLicenseAutoFault'>
				<soap:fault name='PrintLicenseAutoFault' use='literal'/>
			</fault-->
		</operation>

		<operation name='GetPrinterStatus'>
			<soap:operation soapAction='GetPrinterStatus'/>
			<input>
				<soap:body use='literal' namespace='test.message' parts='OriginMachine'/>
			</input>
			<output>
				<soap:body use='literal' namespace='test.message' parts='Result'/>
			</output>
			<!--fault name='GetPrinterStatusFault'>
        			<soap:fault name='GetPrinterStatusFault' use='literal'/>
			</fault-->
		</operation>

	</binding>

	<service name='test' >
		<port name='Job2Port' binding='wsdlns:job2Binding' >
			<soap:address location='http://127.0.0.1/test/test.ASP'/>
		</port>
	</service>

</definitions>
